version: "3.8"
services:
  ruby:
    build: .
    working_dir: /app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis
  redis:
    image: redis:7.2.4-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
